(() => {
  const cfg = window.NIDAN_CONFIG || {};
  const loginView = document.getElementById('loginView'), appView = document.getElementById('appView'), page = document.getElementById('page');
  const loginForm = document.getElementById('loginForm'), loginMessage = document.getElementById('loginMessage'), userEmail = document.getElementById('userEmail'), userRole = document.getElementById('userRole');
  let client=null, sessionUser=null, profile=null;
  const catalog=[
    ['CBC','Complete Blood Count','HB, WBC, RBC, PLT, HCT, MCV, MCH, MCHC, RDW-CV'],['LFT','Liver Function Test','TBIL, DBIL, ALT, AST, ALP, TP, ALB'],['RFT','Renal Function Test','UREA, CREAT, URIC, SOD, POT'],['LIPID','Lipid Profile','TC, TG, HDL, LDL'],['TSH','Thyroid Stimulating Hormone','TSH'],['WIDAL','Widal Test','TO, TH, AH, BH'],['ESR','Erythrocyte Sedimentation Rate','ESR']
  ];
  const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const configured=()=>cfg.supabaseUrl&&cfg.supabasePublishableKey&&!cfg.supabasePublishableKey.startsWith('YOUR_');
  const showLogin=m=>{loginView.classList.remove('hidden');appView.classList.add('hidden');loginMessage.textContent=m||'';};
  const showApp=()=>{loginView.classList.add('hidden');appView.classList.remove('hidden');};
  const canEditPatients=()=>['owner','admin','receptionist'].includes(profile?.role);
  function table(rows,empty='No records found.'){if(!rows.length)return `<div class="empty">${empty}</div>`;const cols=Object.keys(rows[0]).filter(k=>!['tenant_id','id','user_id'].includes(k));return `<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${esc(c.replaceAll('_',' '))}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${esc(r[c])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
  const stat=(label,value,icon)=>`<div class="stat"><div class="stat-icon">${icon}</div><div><div class="stat-value">${value}</div><div class="stat-label">${label}</div></div></div>`;
  async function getProfile(){const {data,error}=await client.from('profiles').select('user_id,tenant_id,email,role,active').eq('user_id',sessionUser.id).single();if(error)throw new Error('Profile not found.');if(!data.active)throw new Error('This laboratory user is inactive.');profile=data;userEmail.textContent=data.email||sessionUser.email||'';userRole.textContent=data.role;}
  async function count(t){const {count:v,error}=await client.from(t).select('*',{count:'exact',head:true});return error?0:v||0;}
  async function dashboard(){page.innerHTML=`<div class="page-head"><div><p class="eyebrow">LAB OVERVIEW</p><h2>Good day, ${esc((profile.email||'').split('@')[0])}</h2><p class="muted">Your NIDAN laboratory workspace is ready.</p></div><button class="primary" data-action="new-patient">+ New Patient</button></div><div class="stats" id="stats">${stat('Patients','…','♙')}${stat('Samples','…','◈')}${stat('Reports','…','▤')}</div><div class="grid-2"><div class="panel"><div class="panel-title">Quick actions</div><div class="quick"><button data-action="new-patient">Register patient</button><button data-action="new-sample">Accession sample</button><button data-action="new-order">Create test order</button><button data-section="reports">Review reports</button></div></div><div class="panel"><div class="panel-title">System status</div><div class="status"><span class="dot"></span> Supabase connected</div><div class="muted small-text">Tenant: ${esc(profile.tenant_id)}</div></div></div>`;const[p,s,r]=await Promise.all([count('patients'),count('samples'),count('reports')]);document.getElementById('stats').innerHTML=`${stat('Patients',p,'♙')}${stat('Samples',s,'◈')}${stat('Reports',r,'▤')}`;}
  async function patients(){page.innerHTML=`<div class="page-head"><div><p class="eyebrow">REGISTRATION</p><h2>Patients</h2><p class="muted">Register and review patients for this laboratory.</p></div><button class="primary" data-action="new-patient">+ New Patient</button></div><div class="panel" id="patientPanel">Loading…</div>`;const{data,error}=await client.from('patients').select('id,patient_id,first_name,last_name,age,sex,created_at').order('created_at',{ascending:false}).limit(50);const panel=document.getElementById('patientPanel');if(error){panel.innerHTML=`<div class="error">${esc(error.message)}</div>`;return;}if(!data?.length){panel.innerHTML='<div class="empty">No patients found.</div>';return;}panel.innerHTML=`<div class="table-wrap"><table><thead><tr><th>Patient ID</th><th>First Name</th><th>Last Name</th><th>Age</th><th>Sex</th><th>Created At</th>${canEditPatients()?'<th>Action</th>':''}</tr></thead><tbody>${data.map(p=>`<tr><td>${esc(p.patient_id)}</td><td>${esc(p.first_name)}</td><td>${esc(p.last_name)}</td><td>${esc(p.age)}</td><td>${esc(p.sex)}</td><td>${esc(p.created_at)}</td>${canEditPatients()?`<td><button class="ghost patient-edit-btn" data-action="edit-patient" data-patient-id="${esc(p.id)}">Edit</button></td>`:''}</tr>`).join('')}</tbody></table></div>`;}
  async function patientEditForm(id){page.innerHTML=`<div class="page-head"><div><p class="eyebrow">PATIENT REGISTRATION</p><h2>Edit Patient</h2><p class="muted">Update the patient's registration details.</p></div><button class="ghost" data-section="patients">← Back</button></div><div class="panel">Loading patient…</div>`;try{const{data,error}=await client.from('patients').select('id,patient_id,first_name,last_name,age,sex').eq('id',id).single();if(error)throw error;if(!data)throw new Error('Patient not found.');page.innerHTML=`<div class="page-head"><div><p class="eyebrow">PATIENT REGISTRATION</p><h2>Edit Patient</h2><p class="muted">Patient ID is kept unchanged so existing samples, orders and reports remain linked.</p></div><button class="ghost" data-section="patients">← Back</button></div><div class="panel"><form id="patientEditForm" class="form-grid"><label>Patient ID<input value="${esc(data.patient_id)}" readonly></label><label>First name<input name="first_name" value="${esc(data.first_name)}" required></label><label>Last name<input name="last_name" value="${esc(data.last_name)}" required></label><label>Age<input name="age" type="number" min="0" max="150" step="1" value="${esc(data.age)}" required></label><label>Sex<select name="sex" required><option value="M" ${data.sex==='M'?'selected':''}>Male</option><option value="F" ${data.sex==='F'?'selected':''}>Female</option><option value="O" ${data.sex==='O'?'selected':''}>Other</option></select></label><div class="form-actions"><button class="primary" type="submit">Save Changes</button><button class="ghost" type="button" data-section="patients">Cancel</button><span id="formMessage" class="message"></span></div></form></div>`;document.getElementById('patientEditForm').onsubmit=e=>savePatientEdit(e,id);}catch(e){page.innerHTML=`<div class="error-card"><h2>Unable to load patient</h2><p>${esc(e.message)}</p><button class="ghost" data-section="patients">← Back to Patients</button></div>`;}}
  async function savePatientEdit(e,id){e.preventDefault();if(!canEditPatients()){document.getElementById('formMessage').textContent='You do not have permission to edit patients.';return;}const p=Object.fromEntries(new FormData(e.target).entries());p.age=Number(p.age);const{error}=await client.from('patients').update({first_name:p.first_name,last_name:p.last_name,age:p.age,sex:p.sex}).eq('id',id);const m=document.getElementById('formMessage');m.textContent=error?error.message:'Patient updated successfully.';if(!error)setTimeout(patients,600);}
  function patientForm(){page.innerHTML=`<div class="page-head"><div><p class="eyebrow">PATIENT REGISTRATION</p><h2>New Patient</h2><p class="muted">Enter the patient's current age. Date of birth is not required.</p></div><button class="ghost" data-section="patients">← Back</button></div><div class="panel"><form id="patientForm" class="form-grid"><label>Patient ID<input name="patient_id" placeholder="NID-0001" required></label><label>First name<input name="first_name" required></label><label>Last name<input name="last_name" required></label><label>Age<input name="age" type="number" min="0" max="150" step="1" placeholder="Years" required></label><label>Sex<select name="sex" required><option value="">Select</option><option value="M">Male</option><option value="F">Female</option><option value="O">Other</option></select></label><div class="form-actions"><button class="primary" type="submit">Save Patient</button><span id="formMessage" class="message"></span></div></form></div>`;document.getElementById('patientForm').onsubmit=savePatient;}
  async function savePatient(e){e.preventDefault();const p=Object.fromEntries(new FormData(e.target).entries());p.tenant_id=profile.tenant_id;p.age=Number(p.age);const{error}=await client.from('patients').insert(p);const m=document.getElementById('formMessage');m.textContent=error?error.message:'Patient saved successfully.';if(!error)setTimeout(patients,600);}
  async function samples(){page.innerHTML=`<div class="page-head"><div><p class="eyebrow">ACCESSIONING</p><h2>Samples</h2><p class="muted">Track incoming specimens and accession numbers.</p></div><button class="primary" data-action="new-sample">+ Accession Sample</button></div><div class="panel" id="samplePanel">Loading…</div>`;const{data,error}=await client.from('samples').select('id,accession_number,patient_id,status,created_at').order('created_at',{ascending:false}).limit(50);document.getElementById('samplePanel').innerHTML=error?`<div class="error">${esc(error.message)}</div>`:table(data||[]);}
  async function loadPatients(){const{data,error}=await client.from('patients').select('id,patient_id,first_name,last_name,age,sex').order('first_name');if(error)throw error;return data||[];}
  async function sampleForm(){page.innerHTML=`<div class="page-head"><div><p class="eyebrow">SAMPLE ACCESSION</p><h2>New Sample</h2></div><button class="ghost" data-section="samples">← Back</button></div><div class="panel">Loading patients…</div>`;try{const ps=await loadPatients();if(!ps.length){page.innerHTML=`<div class="panel notice">Please register a patient first.</div>`;return;}page.innerHTML=`<div class="page-head"><div><p class="eyebrow">SAMPLE ACCESSION</p><h2>New Sample</h2><p class="muted">Select the registered patient; no UUID entry is required.</p></div><button class="ghost" data-section="samples">← Back</button></div><div class="panel"><form id="sampleForm" class="form-grid"><label>Accession number<input name="accession_number" placeholder="NID-2026-0001" required></label><label>Patient<select name="patient_id" required><option value="">Select patient</option>${ps.map(p=>`<option value="${p.id}">${esc(p.patient_id)} — ${esc(p.first_name)} ${esc(p.last_name)} (${p.age}y)</option>`).join('')}</select></label><label>Specimen type<select name="specimen_type" required><option value="Blood">Blood</option><option value="Serum">Serum</option><option value="Plasma">Plasma</option><option value="Urine">Urine</option><option value="Stool">Stool</option><option value="Other">Other</option></select></label><label>Status<select name="status"><option value="received">Received</option><option value="processing">Processing</option><option value="completed">Completed</option></select></label><div class="form-actions"><button class="primary" type="submit">Save Sample</button><span id="formMessage" class="message"></span></div></form></div>`;document.getElementById('sampleForm').onsubmit=saveSample;}catch(e){page.innerHTML=`<div class="error-card"><h2>Unable to load patients</h2><p>${esc(e.message)}</p></div>`;}}
  async function saveSample(e){e.preventDefault();const p=Object.fromEntries(new FormData(e.target).entries());p.tenant_id=profile.tenant_id;const{error}=await client.from('samples').insert(p);document.getElementById('formMessage').textContent=error?error.message:'Sample saved successfully.';if(!error)setTimeout(samples,600);}
  async function loadTestOrders(){const{data,error}=await client.from('test_orders').select('id,order_number,status,patient_id,sample_id,created_at').order('created_at',{ascending:false}).limit(50);return{data,error};}
  async function testOrders(){page.innerHTML=`<div class="page-head"><div><p class="eyebrow">TEST ORDERING</p><h2>Test Orders</h2><p class="muted">Create and track laboratory test orders.</p></div><button class="primary" data-action="new-order">+ New Test Order</button></div><div class="panel" id="orderPanel">Loading…</div>`;const{data,error}=await loadTestOrders();document.getElementById('orderPanel').innerHTML=error?`<div class="error">${esc(error.message)}</div>`:table(data||[],'No test orders yet.');}
  async function newOrder(){page.innerHTML=`<div class="page-head"><div><p class="eyebrow">TEST ORDER</p><h2>Create Test Order</h2><p class="muted">Choose a patient, their sample, and one or more tests.</p></div><button class="ghost" data-section="test-orders">← Back</button></div><div class="panel">Loading…</div>`;try{const[ps,ss]=await Promise.all([loadPatients(),(async()=>{const{data,error}=await client.from('samples').select('id,accession_number,patient_id,status').order('created_at',{ascending:false});if(error)throw error;return data||[];})()]);if(!ps.length){page.innerHTML='<div class="panel notice">Please register a patient first.</div>';return;}if(!ss.length){page.innerHTML='<div class="panel notice">Please accession a sample first.</div>';return;}page.innerHTML=`<div class="page-head"><div><p class="eyebrow">TEST ORDER</p><h2>Create Test Order</h2></div><button class="ghost" data-section="test-orders">← Back</button></div><div class="panel"><form id="orderForm" class="form-grid"><label>Patient<select id="orderPatient" name="patient_id" required><option value="">Select patient</option>${ps.map(p=>`<option value="${p.id}">${esc(p.patient_id)} — ${esc(p.first_name)} ${esc(p.last_name)} (${p.age}y)</option>`).join('')}</select></label><label>Sample<select id="orderSample" name="sample_id" required><option value="">Select sample</option>${ss.map(s=>`<option value="${s.id}" data-patient="${s.patient_id}">${esc(s.accession_number)} — ${esc(s.status)}</option>`).join('')}</select></label><label>Order number<input name="order_number" value="NID-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${String(Date.now()).slice(-5)}" required></label><div class="test-picker"><div class="panel-title">Select Tests</div>${catalog.map(([code,name,params])=>`<label class="check-card"><input type="checkbox" name="tests" value="${code}" data-name="${esc(name)}"><span><strong>${esc(code)} — ${esc(name)}</strong><small>${esc(params)}</small></span></label>`).join('')}</div><div class="form-actions"><button class="primary" type="submit">Create Test Order</button><span id="formMessage" class="message"></span></div></form></div>`;const patientSel=document.getElementById('orderPatient'),sampleSel=document.getElementById('orderSample');patientSel.onchange=()=>{[...sampleSel.options].forEach(o=>{if(o.value)o.hidden=o.dataset.patient!==patientSel.value;});sampleSel.value='';};document.getElementById('orderForm').onsubmit=saveOrder;}catch(e){page.innerHTML=`<div class="error-card"><h2>Unable to load</h2><p>${esc(e.message)}</p></div>`;}}
  async function saveOrder(e){e.preventDefault();const f=new FormData(e.target),patient_id=f.get('patient_id'),sample_id=f.get('sample_id'),order_number=f.get('order_number');const tests=[...document.querySelectorAll('input[name="tests"]:checked')].map(x=>({code:x.value,name:x.dataset.name}));const msg=document.getElementById('formMessage');if(!tests.length){msg.textContent='Select at least one test.';return;}const order={tenant_id:profile.tenant_id,patient_id,sample_id,order_number,status:'ordered',ordered_by:sessionUser.id};const{data,error}=await client.from('test_orders').insert(order).select('id').single();if(error){msg.textContent=error.message;return;}const items=tests.map(t=>({tenant_id:profile.tenant_id,order_id:data.id,test_code:t.code,test_name:t.name,status:'ordered',result_data:{}}));const{error:itemError}=await client.from('test_order_items').insert(items);if(itemError){await client.from('test_orders').delete().eq('id',data.id);msg.textContent=itemError.message;return;}msg.textContent=`Order ${order_number} created successfully.`;setTimeout(testOrders,800);}
  function tests(){page.innerHTML=`<div class="page-head"><div><p class="eyebrow">TEST CATALOG</p><h2>Laboratory Tests</h2><p class="muted">Starter catalog; reference intervals remain lab/method specific.</p></div></div><div class="catalog">${catalog.map(([c,n,p])=>`<div class="test-card"><span class="code">${c}</span><h3>${n}</h3><p>${p}</p></div>`).join('')}</div>`;}
  function results(){page.innerHTML=`<div class="page-head"><div><p class="eyebrow">RESULT ENTRY</p><h2>Results</h2><p class="muted">Test orders are now ready for result entry.</p></div></div><div class="panel notice"><strong>Next:</strong> select an order → enter parameter values → technician/pathologist verification → report release.</div>`;}
  async function reports(){page.innerHTML=`<div class="page-head"><div><p class="eyebrow">REPORTING</p><h2>Reports</h2><p class="muted">View report records for this laboratory.</p></div></div><div class="panel" id="reportPanel">Loading…</div>`;const{data,error}=await client.from('reports').select('sample_id,status,created_at,verified_at,released_at').order('created_at',{ascending:false}).limit(50);document.getElementById('reportPanel').innerHTML=error?`<div class="error">${esc(error.message)}</div>`:table(data||[],'No reports yet.');}
  function simplePage(title,eyebrow,text){page.innerHTML=`<div class="page-head"><div><p class="eyebrow">${eyebrow}</p><h2>${title}</h2><p class="muted">${text}</p></div></div><div class="panel notice">This module is scheduled for the next implementation step.</div>`;}
  async function openSection(s){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.section===s));try{if(s==='dashboard')await dashboard();else if(s==='patients')await patients();else if(s==='samples')await samples();else if(s==='test-orders')await testOrders();else if(s==='tests')tests();else if(s==='results')results();else if(s==='reports')await reports();else if(s==='billing')simplePage('Billing','FINANCE','Invoices, payments and outstanding balances.');else if(s==='doctors')simplePage('Doctors & Referrals','REFERRALS','Referring doctors and clinic management.');else simplePage('Settings','ADMINISTRATION','Laboratory profile, users and configuration.');}catch(e){page.innerHTML=`<div class="error-card"><h2>Unable to load</h2><p>${esc(e.message)}</p></div>`;}}
  document.addEventListener('click',e=>{const nav=e.target.closest('[data-section]');if(nav)openSection(nav.dataset.section);const a=e.target.closest('[data-action]');if(a){if(a.dataset.action==='new-patient')patientForm();if(a.dataset.action==='new-sample')sampleForm();if(a.dataset.action==='new-order')newOrder();if(a.dataset.action==='edit-patient')patientEditForm(a.dataset.patientId);}});
  document.getElementById('logoutBtn').onclick=async()=>{if(client)await client.auth.signOut();sessionUser=null;profile=null;showLogin('Signed out.');};
  loginForm.onsubmit=async e=>{e.preventDefault();loginMessage.textContent='Signing in…';if(!configured()){loginMessage.textContent='Frontend configuration is incomplete.';return;}try{const{error}=await client.auth.signInWithPassword({email:document.getElementById('email').value,password:document.getElementById('password').value});if(error)throw error;}catch(err){loginMessage.textContent=err.message;}};
  async function init(){if(!configured()){showLogin('Frontend configuration is incomplete.');return;}client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);const{data}=await client.auth.getSession();if(data.session){sessionUser=data.session.user;try{await getProfile();showApp();openSection('dashboard');}catch(e){showLogin(e.message);}}else showLogin();client.auth.onAuthStateChange((_event,s)=>{if(s){sessionUser=s.user;getProfile().then(()=>{showApp();openSection('dashboard');}).catch(e=>showLogin(e.message));}});}
  init();
})();