(() => {
  const cfg=window.NIDAN_CONFIG||{};
  if(!cfg.supabaseUrl||!cfg.supabasePublishableKey||cfg.supabasePublishableKey.startsWith('YOUR_'))return;
  const db=supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey), page=document.getElementById('page');
  const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const catalog=[['CBC','Complete Blood Count'],['LFT','Liver Function Test'],['RFT','Renal Function Test'],['LIPID','Lipid Profile'],['TSH','Thyroid Stimulating Hormone'],['WIDAL','Widal Test'],['ESR','Erythrocyte Sedimentation Rate']];
  async function ctx(){const {data:{user}}=await db.auth.getUser();if(!user)throw Error('Session expired');const {data:p,error}=await db.from('profiles').select('tenant_id,role,email').eq('user_id',user.id).single();if(error)throw error;return{user,p};}
  async function patients(){const {data,error}=await db.from('patients').select('id,patient_id,first_name,last_name,age').order('first_name');if(error)throw error;return data||[];}
  async function doctors(){const {data,error}=await db.from('doctors').select('id,doctor_code,name,qualification,specialty,phone,clinic,active,created_at').order('name');if(error)throw error;return data||[];}
  async function invoices(){const {data,error}=await db.from('invoices').select('id,invoice_number,patient_id,sample_id,status,subtotal,discount,total,paid,balance,created_at').order('created_at',{ascending:false}).limit(50);if(error)throw error;return data||[];}
  async function billingHome(){page.innerHTML=`<div class="page-head"><div><p class="eyebrow">FINANCE</p><h2>Billing</h2><p class="muted">Create invoices, record payments and track outstanding balances.</p></div><div class="workflow-actions"><button class="primary" data-billing="new">+ New Invoice</button><button class="ghost" data-billing="pay">Record Payment</button></div></div><div class="panel" id="billingPanel">Loading…</div>`;try{const rows=await invoices();page.querySelector('#billingPanel').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Invoice</th><th>Patient</th><th>Status</th><th>Total</th><th>Paid</th><th>Balance</th><th>Created</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.invoice_number)}</td><td>${esc(r.patient_id)}</td><td>${esc(r.status)}</td><td>₹${Number(r.total||0).toFixed(2)}</td><td>₹${Number(r.paid||0).toFixed(2)}</td><td>₹${Number(r.balance||0).toFixed(2)}</td><td>${new Date(r.created_at).toLocaleString()}</td><td>${Number(r.balance)>0?`<button class="ghost small-btn" data-billing-pay="${r.id}">Pay</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No invoices yet.</div>';}catch(e){page.querySelector('#billingPanel').innerHTML=`<div class="error">${esc(e.message)}</div>`;}}
  async function newInvoice(){page.innerHTML='<div class="panel">Loading billing form…</div>';try{const ps=await patients();page.innerHTML=`<div class="page-head"><div><p class="eyebrow">INVOICE</p><h2>New Invoice</h2><p class="muted">Add one or more laboratory services.</p></div><button class="ghost" data-billing="home">← Back</button></div><div class="panel"><form id="invoiceForm" class="form-grid"><label>Patient<select name="patient_id" required><option value="">Select patient</option>${ps.map(p=>`<option value="${p.id}">${esc(p.patient_id)} — ${esc(p.first_name)} ${esc(p.last_name)} (${esc(p.age)}y)</option>`).join('')}</select></label><label>Invoice number<input name="invoice_number" value="NID-INV-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${String(Date.now()).slice(-5)}" required></label><div class="test-picker"><div class="panel-title">Services & Charges</div>${catalog.map(([c,n])=>`<label class="check-card"><input type="checkbox" name="svc" value="${c}" data-name="${esc(n)}"><span><strong>${c} — ${esc(n)}</strong><input class="line-amount" data-amount-for="${c}" type="number" min="0" step="0.01" value="0" placeholder="Amount (₹)" disabled></span></label>`).join('')}</div><label>Discount (₹)<input id="discount" name="discount" type="number" min="0" step="0.01" value="0"></label><div class="invoice-totals"><span>Subtotal <b id="subtotal">₹0.00</b></span><span>Total <b id="total">₹0.00</b></span></div><div class="form-actions"><button class="primary" type="submit">Create Invoice</button><span id="invoiceMsg" class="message"></span></div></form></div>`;page.querySelectorAll('input[name="svc"]').forEach(c=>c.onchange=()=>{page.querySelector(`[data-amount-for="${c.value}"]`).disabled=!c.checked;calcInvoice();});page.querySelectorAll('.line-amount,#discount').forEach(x=>x.oninput=calcInvoice);page.querySelector('#invoiceForm').onsubmit=saveInvoice;}catch(e){page.innerHTML=`<div class="error-card"><h2>Unable to open billing</h2><p>${esc(e.message)}</p></div>`;}}
  function calcInvoice(){let sub=0;page.querySelectorAll('input[name="svc"]:checked').forEach(c=>{sub+=Number(page.querySelector(`[data-amount-for="${c.value}"]`).value||0);});const d=Math.max(0,Number(document.getElementById('discount')?.value||0));const total=Math.max(0,sub-d);document.getElementById('subtotal').textContent=`₹${sub.toFixed(2)}`;document.getElementById('total').textContent=`₹${total.toFixed(2)}`;return{sub,d,total};}
  async function saveInvoice(e){e.preventDefault();try{const {user,p}=await ctx(),f=new FormData(e.target),x=calcInvoice();if(!f.get('patient_id'))throw Error('Select a patient.');if(x.sub<=0)throw Error('Add at least one service with an amount greater than zero.');if(x.d>x.sub)throw Error('Discount cannot exceed subtotal.');const row={tenant_id:p.tenant_id,invoice_number:f.get('invoice_number'),patient_id:f.get('patient_id'),status:'unpaid',subtotal:x.sub,discount:x.d,total:x.total,paid:0,balance:x.total,created_by:user.id};const {data,error}=await db.from('invoices').insert(row).select('id,invoice_number').single();if(error)throw error;const items=[...page.querySelectorAll('input[name="svc"]:checked')].map(c=>({tenant_id:p.tenant_id,invoice_id:data.id,test_code:c.value,test_name:c.dataset.name,amount:Number(page.querySelector(`[data-amount-for="${c.value}"]`).value||0)}));const ir=await db.from('invoice_items').insert(items);if(ir.error){await db.from('invoices').delete().eq('id',data.id);throw ir.error;}document.getElementById('invoiceMsg').textContent=`Invoice ${data.invoice_number} created successfully.`;setTimeout(billingHome,700);}catch(e){document.getElementById('invoiceMsg').textContent=e.message;}}
  async function paymentForm(invoiceId=null){try{const rows=await invoices();const target=invoiceId?rows.find(x=>x.id===invoiceId):null;page.innerHTML=`<div class="page-head"><div><p class="eyebrow">PAYMENT</p><h2>Record Payment</h2><p class="muted">Payments are posted atomically and update the invoice balance.</p></div><button class="ghost" data-billing="home">← Back</button></div><div class="panel"><form id="paymentForm" class="form-grid"><label>Invoice<select id="payInvoice" name="invoice_id" required><option value="">Select invoice</option>${rows.filter(r=>Number(r.balance)>0).map(r=>`<option value="${r.id}" ${target?.id===r.id?'selected':''}>${esc(r.invoice_number)} — Patient ${esc(r.patient_id)} — Balance ₹${Number(r.balance).toFixed(2)}</option>`).join('')}</select></label><label>Amount (₹)<input id="payAmount" name="amount" type="number" min="0.01" step="0.01" required value="${target?Number(target.balance).toFixed(2):''}"></label><label>Method<select name="method"><option value="cash">Cash</option><option value="upi">UPI</option><option value="card">Card</option><option value="bank_transfer">Bank Transfer</option><option value="other">Other</option></select></label><label>Reference<input name="reference" placeholder="UPI/transaction/reference number"></label><div class="form-actions"><button class="primary" type="submit">Save Payment</button><span id="paymentMsg" class="message"></span></div></form></div>`;document.getElementById('paymentForm').onsubmit=savePayment;}catch(e){page.innerHTML=`<div class="error-card"><h2>Unable to open payments</h2><p>${esc(e.message)}</p></div>`;}}
  async function savePayment(e){e.preventDefault();const f=new FormData(e.target),{data,error}=await db.rpc('nidan_record_payment',{p_invoice_id:f.get('invoice_id'),p_amount:Number(f.get('amount')),p_method:f.get('method'),p_reference:f.get('reference')||null});const m=document.getElementById('paymentMsg');m.textContent=error?error.message:`Payment saved. Balance ₹${Number(data.balance).toFixed(2)}.`;if(!error)setTimeout(billingHome,800);}
  async function doctorsHome(){page.innerHTML=`<div class="page-head"><div><p class="eyebrow">REFERRALS</p><h2>Doctors</h2><p class="muted">Maintain referring doctor records for this laboratory.</p></div><button class="primary" data-doctors="new">+ Add Doctor</button></div><div class="panel" id="doctorPanel">Loading…</div>`;try{const rows=await doctors();page.querySelector('#doctorPanel').innerHTML=rows.length?tableDoctors(rows):'<div class="empty">No doctors added yet.</div>';}catch(e){page.querySelector('#doctorPanel').innerHTML=`<div class="error">${esc(e.message)}</div>`;}}
  function tableDoctors(rows){return`<div class="table-wrap"><table><thead><tr><th>Code</th><th>Name</th><th>Qualification</th><th>Specialty</th><th>Phone</th><th>Clinic</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(d=>`<tr><td>${esc(d.doctor_code)}</td><td>${esc(d.name)}</td><td>${esc(d.qualification)}</td><td>${esc(d.specialty)}</td><td>${esc(d.phone)}</td><td>${esc(d.clinic)}</td><td>${d.active?'Active':'Inactive'}</td><td><button class="ghost small-btn" data-doctor-edit="${d.id}">Edit</button></td></tr>`).join('')}</tbody></table></div>`;}
  async function doctorForm(id=null){const rows=await doctors(),d=id?rows.find(x=>x.id===id):null;page.innerHTML=`<div class="page-head"><div><p class="eyebrow">REFERRING DOCTOR</p><h2>${d?'Edit':'Add'} Doctor</h2></div><button class="ghost" data-doctors="home">← Back</button></div><div class="panel"><form id="doctorForm" class="form-grid"><label>Doctor code<input name="doctor_code" required value="${esc(d?.doctor_code||'DR-001')}"></label><label>Name<input name="name" required value="${esc(d?.name||'')}"></label><label>Qualification<input name="qualification" placeholder="MBBS, MD" value="${esc(d?.qualification||'')}"></label><label>Specialty<input name="specialty" placeholder="Medicine, Pathology…" value="${esc(d?.specialty||'')}"></label><label>Phone<input name="phone" value="${esc(d?.phone||'')}"></label><label>Clinic / Hospital<input name="clinic" value="${esc(d?.clinic||'')}"></label><label>Active<select name="active"><option value="true" ${d?.active!==false?'selected':''}>Active</option><option value="false" ${d?.active===false?'selected':''}>Inactive</option></select></label><div class="form-actions"><button class="primary" type="submit">Save Doctor</button><span id="doctorMsg" class="message"></span></div></form></div>`;document.getElementById('doctorForm').onsubmit=e=>saveDoctor(e,id);}
  async function saveDoctor(e,id){e.preventDefault();try{const {p}=await ctx(),f=new FormData(e.target),row={tenant_id:p.tenant_id,doctor_code:f.get('doctor_code').trim(),name:f.get('name').trim(),qualification:f.get('qualification').trim()||null,specialty:f.get('specialty').trim()||null,phone:f.get('phone').trim()||null,clinic:f.get('clinic').trim()||null,active:f.get('active')==='true'};const q=id?db.from('doctors').update(row).eq('id',id):db.from('doctors').insert(row);const {error}=await q;document.getElementById('doctorMsg').textContent=error?error.message:'Doctor saved successfully.';if(!error)setTimeout(doctorsHome,700);}catch(e){document.getElementById('doctorMsg').textContent=e.message;}}
  function table(rows,empty='No records'){if(!rows.length)return`<div class="empty">${empty}</div>`;return `<div class="table-wrap"><table><thead><tr>${Object.keys(rows[0]).map(k=>`<th>${esc(k.replaceAll('_',' '))}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${Object.keys(rows[0]).map(k=>`<td>${esc(r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-billing]');if(b){const a=b.dataset.billing;if(a==='home')billingHome();if(a==='new')newInvoice();if(a==='pay')paymentForm();return;}const p=e.target.closest('[data-billing-pay]');if(p)return paymentForm(p.dataset.billingPay);const d=e.target.closest('[data-doctors]');if(d){const a=d.dataset.doctors;if(a==='home')doctorsHome();if(a==='new')doctorForm();return;}const de=e.target.closest('[data-doctor-edit]');if(de)return doctorForm(de.dataset.doctorEdit);});
  document.addEventListener('click',e=>{const n=e.target.closest('.nav');if(!n)return;if(n.dataset.section==='billing')setTimeout(billingHome,0);if(n.dataset.section==='doctors')setTimeout(doctorsHome,0);});
  window.NIDAN_BILLING={billingHome,doctorsHome};
})();
