(() => {
  const cfg = window.NIDAN_CONFIG || {};
  if (!cfg.supabaseUrl || !cfg.supabasePublishableKey || cfg.supabasePublishableKey.startsWith('YOUR_')) return;
  const client = supabase.createClient(cfg.supabaseUrl, cfg.supabasePublishableKey);
  const page = document.getElementById('page');
  const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const catalogs = {
    CBC:[['HB','Hemoglobin','g/dL'],['WBC','WBC','10^3/µL'],['RBC','RBC','10^6/µL'],['PLT','Platelet','10^3/µL'],['HCT','Hematocrit','%'],['MCV','MCV','fL'],['MCH','MCH','pg'],['MCHC','MCHC','g/dL'],['RDW_CV','RDW-CV','%']],
    LFT:[['TBIL','Total Bilirubin','mg/dL'],['DBIL','Direct Bilirubin','mg/dL'],['ALT','ALT','U/L'],['AST','AST','U/L'],['ALP','ALP','U/L'],['TP','Total Protein','g/dL'],['ALB','Albumin','g/dL']],
    RFT:[['UREA','Urea','mg/dL'],['CREAT','Creatinine','mg/dL'],['URIC','Uric Acid','mg/dL'],['SOD','Sodium','mmol/L'],['POT','Potassium','mmol/L']],
    LIPID:[['TC','Total Cholesterol','mg/dL'],['TG','Triglycerides','mg/dL'],['HDL','HDL','mg/dL'],['LDL','LDL','mg/dL']],
    TSH:[['TSH','TSH','µIU/mL']], WIDAL:[['TO','S. typhi O','Titre'],['TH','S. typhi H','Titre'],['AH','S. paratyphi AH','Titre'],['BH','S. paratyphi BH','Titre']], ESR:[['ESR','ESR','mm/hr']]
  };
  const canVerify = role => ['owner','admin','pathologist'].includes(role);
  const canEnter = role => ['owner','admin','technician'].includes(role);
  async function session(){const {data:{session}}=await client.auth.getSession();return session;}
  async function profileFor(u){const {data,error}=await client.from('profiles').select('tenant_id,role,email').eq('user_id',u.id).single();if(error)throw error;return data;}
  async function loadOrders(){const {data,error}=await client.from('test_orders').select('id,order_number,status,patient_id,sample_id,created_at').order('created_at',{ascending:false}).limit(50);if(error)throw error;return data||[];}
  async function loadItems(orderId){const {data,error}=await client.from('test_order_items').select('id,test_code,test_name,status,result_data,created_at').eq('order_id',orderId).order('created_at');if(error)throw error;return data||[];}
  async function patient(id){const {data,error}=await client.from('patients').select('patient_id,first_name,last_name,age,sex').eq('id',id).single();if(error)throw error;return data;}
  async function sample(id){const {data,error}=await client.from('samples').select('accession_number,status,specimen_type,patient_id').eq('id',id).single();if(error)throw error;return data;}
  function resultFields(item){const fields=catalogs[item.test_code]||[[item.test_code,item.test_name,'']];const old=item.result_data||{};return fields.map(([code,label,unit])=>`<div class="result-field"><label>${esc(label)}<input name="${esc(code)}" value="${esc(old[code]??'')}" placeholder="Enter result" ${item.status==='verified'||item.status==='released'?'disabled':''}><small>${esc(unit)}</small></label></div>`).join('');}
  async function resultsHome(){page.innerHTML='<div class="page-head"><div><p class="eyebrow">RESULT ENTRY</p><h2>Results</h2><p class="muted">Select an order to enter laboratory results and start verification.</p></div></div><div class="panel" id="workflowPanel">Loading test orders…</div>';try{const orders=await loadOrders();page.querySelector('#workflowPanel').innerHTML=orders.length?orders.map(o=>`<button class="workflow-row" data-result-order="${o.id}"><span><strong>${esc(o.order_number)}</strong><small>Patient ID: ${esc(o.patient_id)} · Sample: ${esc(o.sample_id)}</small></span><b>${esc(o.status)}</b></button>`).join(''):'<div class="empty">No test orders yet. Create a test order first.</div>';}catch(e){page.querySelector('#workflowPanel').innerHTML=`<div class="error">${esc(e.message)}</div>`;}}
  async function resultOrder(orderId){page.innerHTML='<div class="panel">Loading order…</div>';try{const orders=await loadOrders();const o=orders.find(x=>x.id===orderId);if(!o)throw new Error('Order not found');const [items,p,s]=await Promise.all([loadItems(orderId),patient(o.patient_id),sample(o.sample_id)]);const sess=await session();const prof=await profileFor(sess.user);page.innerHTML=`<div class="page-head"><div><p class="eyebrow">RESULT ENTRY</p><h2>${esc(o.order_number)}</h2><p class="muted">${esc(p.patient_id)} — ${esc(p.first_name)} ${esc(p.last_name)} · Age ${esc(p.age)} · ${esc(s.accession_number)}</p></div><button class="ghost" data-workflow="results-home">← Back</button></div><div class="panel"><div class="patient-strip"><strong>${esc(p.first_name)} ${esc(p.last_name)}</strong><span>Age ${esc(p.age)}</span><span>${esc(p.sex)}</span><span>Sample ${esc(s.accession_number)}</span></div>${items.map(i=>`<form class="result-card" data-result-item="${i.id}" data-test-code="${esc(i.test_code)}"><div class="result-head"><div><span class="code">${esc(i.test_code)}</span><h3>${esc(i.test_name)}</h3></div><span class="status-pill">${esc(i.status)}</span></div><div class="result-grid">${resultFields(i)}</div>${i.status==='verified'||i.status==='released'?'<p class="muted small-text">Verified result — values are locked.</p>':canEnter(prof.role)?'<div class="form-actions"><button class="primary" type="submit">Save Result</button><span class="message result-message"></span></div>':'<p class="muted">You do not have permission to enter results.</p>'}</form>`).join('')}</div>`;page.querySelectorAll('[data-result-item]').forEach(f=>f.onsubmit=e=>saveResult(e,o.id));}catch(e){page.innerHTML=`<div class="error-card"><h2>Unable to open result entry</h2><p>${esc(e.message)}</p></div>`;}}
  async function saveResult(e,orderId){e.preventDefault();const form=e.currentTarget,itemId=form.dataset.resultItem;const result={};form.querySelectorAll('input[name]').forEach(i=>{result[i.name]=i.value.trim();});const {error}=await client.from('test_order_items').update({result_data:result,status:'result_entered'}).eq('id',itemId);const msg=form.querySelector('.result-message');msg.textContent=error?error.message:'Result saved successfully.';if(!error)setTimeout(()=>resultOrder(orderId),500);}
  async function verificationHome(){page.innerHTML='<div class="page-head"><div><p class="eyebrow">VERIFICATION & RELEASE</p><h2>Reports</h2><p class="muted">Verify completed results, generate a report and release it.</p></div></div><div class="panel" id="reportWorkflow">Loading…</div>';try{const sess=await session();if(!sess)throw new Error('Session expired');const prof=await profileFor(sess.user);const orders=await loadOrders();const rows=[];for(const o of orders){const items=await loadItems(o.id);if(items.some(i=>['result_entered','verified','released'].includes(i.status))){rows.push({o,items});}}page.querySelector('#reportWorkflow').innerHTML=rows.length?rows.map(({o,items})=>{const done=items.filter(i=>i.status!=='cancelled').length,ver=items.filter(i=>['verified','released'].includes(i.status)).length;return `<div class="workflow-row report-row"><div><strong>${esc(o.order_number)}</strong><small>${ver}/${done} tests verified · Sample ${esc(o.sample_id)}</small></div><div class="workflow-actions">${canVerify(prof.role)&&items.some(i=>i.status==='result_entered')?`<button class="primary small-btn" data-verify-order="${o.id}">Verify Results</button>`:''}<button class="ghost small-btn" data-open-report="${o.sample_id}">Open Report</button></div></div>`}).join(''):'<div class="empty">No entered results waiting for verification.</div>';}catch(e){page.querySelector('#reportWorkflow').innerHTML=`<div class="error">${esc(e.message)}</div>`;}}
  async function verifyOrder(orderId){const items=await loadItems(orderId);for(const i of items.filter(x=>x.status==='result_entered')){const {error}=await client.rpc('nidan_verify_test_item',{p_item_id:i.id});if(error){alert(error.message);return;}}alert('All entered results were verified.');verificationHome();}
  async function openReport(sampleId){page.innerHTML='<div class="panel">Loading report…</div>';try{const sess=await session(),prof=await profileFor(sess.user),s=await sample(sampleId),p=await patient(s.patient_id);let {data:report,error}=await client.from('reports').select('*').eq('sample_id',sampleId).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;if(!report){const r=await client.rpc('nidan_create_draft_report',{p_sample_id:sampleId});if(r.error)throw r.error;report=r.data;}const {data:items,error:itemError}=await client.from('test_order_items').select('test_code,test_name,status,result_data,created_at,test_orders!inner(sample_id)').eq('test_orders.sample_id',sampleId).neq('status','cancelled').order('created_at');if(itemError)throw itemError;const released=report.status==='released';page.innerHTML=`<div class="page-head"><div><p class="eyebrow">LABORATORY REPORT</p><h2>${esc(report.report_number||'Draft Report')}</h2><p class="muted">${esc(p.patient_id)} — ${esc(p.first_name)} ${esc(p.last_name)} · Age ${esc(p.age)} · Sample ${esc(s.accession_number)}</p></div><div class="workflow-actions"><button class="ghost" data-workflow="reports-home">← Back</button><button class="ghost" data-print-report="${report.id}">Print / PDF</button>${canVerify(prof.role)&&!released?`<button class="primary" data-release-report="${report.id}">Release Report</button>`:''}</div></div><div class="panel report-paper"><div class="report-brand"><div class="brand-mark">N</div><div><h2>NIDAN PATHOLOGY LAB</h2><p>Laboratory Information System</p></div></div><hr><div class="patient-strip"><span><b>Patient:</b> ${esc(p.first_name)} ${esc(p.last_name)}</span><span><b>Age:</b> ${esc(p.age)}</span><span><b>Sex:</b> ${esc(p.sex)}</span><span><b>Sample:</b> ${esc(s.accession_number)}</span></div><table><thead><tr><th>Test</th><th>Result</th><th>Unit</th><th>Status</th></tr></thead><tbody>${items.map(i=>{const vals=Object.entries(i.result_data||{});return vals.length?vals.map(([k,v])=>{const spec=(catalogs[i.test_code]||[]).find(x=>x[0]===k);return `<tr><td>${esc(i.test_name)} — ${esc(spec?spec[1]:k)}</td><td><b>${esc(v)}</b></td><td>${esc(spec?spec[2]:'')}</td><td>${esc(i.status)}</td></tr>`}).join(''):`<tr><td>${esc(i.test_name)}</td><td>—</td><td></td><td>${esc(i.status)}</td></tr>`}).join('')}</tbody></table><p class="muted small-text">Reference intervals are laboratory/method specific and should be configured before clinical use.</p><div class="report-sign"><div>Verified by<br><strong>${report.verified_by?'Authorized user':'Pending'}</strong></div><div>Released<br><strong>${released?'Released':'Draft'}</strong></div></div></div>`;}catch(e){page.innerHTML=`<div class="error-card"><h2>Unable to open report</h2><p>${esc(e.message)}</p></div>`;}}
  async function releaseReport(reportId){if(!confirm('Release this report? Released results should not be edited casually.'))return;const {data,error}=await client.rpc('nidan_release_report',{p_report_id:reportId});if(error){alert(error.message);return;}alert(`Report ${data.report_number||''} released successfully.`);openReport(data.sample_id);}
  async function printReport(reportId){const {data:report,error}=await client.from('reports').select('*').eq('id',reportId).single();if(error){alert(error.message);return;}const s=await sample(report.sample_id),p=await patient(s.patient_id);const {data:items}=await client.from('test_order_items').select('test_code,test_name,status,result_data,test_orders!inner(sample_id)').eq('test_orders.sample_id',s.id).neq('status','cancelled').order('created_at');const rows=(items||[]).flatMap(i=>Object.entries(i.result_data||{}).map(([k,v])=>{const spec=(catalogs[i.test_code]||[]).find(x=>x[0]===k);return `<tr><td>${esc(i.test_name)} — ${esc(spec?spec[1]:k)}</td><td>${esc(v)}</td><td>${esc(spec?spec[2]:'')}</td><td>${esc(i.status)}</td></tr>`;})).join('');const w=window.open('','_blank');if(!w){alert('Allow pop-ups to print the report.');return;}w.document.write(`<!doctype html><html><head><title>${esc(report.report_number||'NIDAN Report')}</title><style>body{font-family:Arial,sans-serif;padding:32px;color:#17212b}h1{font-size:24px}h2{margin-bottom:2px}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{border:1px solid #ccc;padding:9px;text-align:left}th{background:#f2f5f5}.meta{display:flex;gap:30px;flex-wrap:wrap;border:1px solid #ddd;padding:12px}.sign{display:flex;justify-content:space-between;margin-top:70px}</style></head><body><h1>NIDAN PATHOLOGY LAB</h1><h2>Laboratory Report</h2><p>Report No: ${esc(report.report_number||'')}</p><div class="meta"><span>Patient: <b>${esc(p.first_name)} ${esc(p.last_name)}</b></span><span>Age: <b>${esc(p.age)}</b></span><span>Sex: <b>${esc(p.sex)}</b></span><span>Sample: <b>${esc(s.accession_number)}</b></span></div><table><thead><tr><th>Test</th><th>Result</th><th>Unit</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table><div class="sign"><span>Verified by: Authorized user</span><span>Released: ${report.released_at?'Yes':'No'}</span></div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close();}
  document.addEventListener('click',e=>{const r=e.target.closest('[data-result-order]');if(r)return resultOrder(r.dataset.resultOrder);const v=e.target.closest('[data-verify-order]');if(v)return verifyOrder(v.dataset.verifyOrder);const o=e.target.closest('[data-open-report]');if(o)return openReport(o.dataset.openReport);const rel=e.target.closest('[data-release-report]');if(rel)return releaseReport(rel.dataset.releaseReport);const pr=e.target.closest('[data-print-report]');if(pr)return printReport(pr.dataset.printReport);const wh=e.target.closest('[data-workflow]');if(wh){if(wh.dataset.workflow==='results-home')resultsHome();if(wh.dataset.workflow==='reports-home')verificationHome();}});
  document.addEventListener('click',e=>{const nav=e.target.closest('.nav');if(!nav)return;const s=nav.dataset.section;if(s==='results'){setTimeout(resultsHome,0);}if(s==='reports'){setTimeout(verificationHome,0);}});
  window.NIDAN_WORKFLOW={resultsHome,verificationHome};
})();
